### ISSUE TITLE
Merge the TEE and non-TEE runtime instances

### ISSUE THREAD

**Issue by Yawning** [oasislabs/oasis-runtime#550]
There needs to be support for a single combined worldview between non-TEE runtime instance, and TEE enabled runtime instances, to enable cross contract calls among other things.

 * [ ] [Scheduler scheduling execution of sgx / confidential contracts](https://github.com/oasislabs/ekiden/issues/1082)
 * [ ] Figure out what exactly is involved in making cross contract calls.
   * [ ] Figure out Ekiden changes required to support a combined TEE/non-TEE runtime.
   * [ ] Figure out Runtime changes required to support a combined TE/non-TEE runtime.
 * [ ] Implement the things to make it happen.
